title: Joe Schlessinger's Blog
author: Joe Schlessinger
email: joe.c.schlessinger@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Mediocre thoughts and code, but it's all I've got.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Joe Schlessinger
  tagline: Meandering dilettante.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: joeschless
    github:  jschless 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#  - about.md
# - resume.html


# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed